const SET_HORSES = 'SET_HORSES';
const SET_ROUNDS = 'SET_ROUNDS';
const SET_CURRENT_ROUND = 'SET_CURRENT_ROUND';
const ADD_RACE_RESULT = 'ADD_RACE_RESULT';
const SET_IS_RACE_STARTED = 'SET_IS_RACE_STARTED';
const SET_IS_RACE_FINISHED = 'SET_IS_RACE_FINISHED';
const RESET_ALL = 'RESET_ALL';

export {SET_HORSES,SET_ROUNDS,SET_CURRENT_ROUND,SET_IS_RACE_FINISHED,SET_IS_RACE_STARTED,RESET_ALL,ADD_RACE_RESULT}

